export const SET_RELEASES_FILMS = "SET_RELEASES_FILMS";
export const SET_TOTAL_ELEMENTS = "SET_TOTAL_ELEMENTS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_IS_FETCHING = "SET_IS_FETCHING";