export const SET_SERIES = "SET_SERIES";
export const SET_TOTAL_ELEMENTS_SERIES = "SET_TOTAL_ELEMENTS_SERIES";
export const SET_CURRENT_PAGE_SERIES = "SET_CURRENT_PAGE_SERIES";
export const SET_IS_FETCHING_SERIES = "SET_IS_FETCHING_SERIES";